function printNameLovesFood() {
    console.log("Hi, my name is Verrol and I love blueberry pie")
}

printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
printNameLovesFood()
